#!/bin/bash
# Submitted at: $(date +%Y-%m-%d\ %H:%M:%S)
#SBATCH --chdir /users/jsyu/Genesis/dexmachinaFork
#SBATCH --nodes 1
#SBATCH --cpus-per-task 8
#SBATCH --ntasks 1
#SBATCH --mem 40G
#SBATCH --gres=gpu:1
#SBATCH --qos=normal
#SBATCH --output=logs/allegro/multi_demo/slurm-%j/slurm-%j.out
#SBATCH --error=logs/allegro/multi_demo/slurm-%j/slurm-%j.err
#SBATCH --mail-user=jeffrey.yu@epfl.ch
#SBATCH --mail-type=END,FAIL
#SBATCH --time 72:00:00

echo "Starting dexmachina allegro training on $HOSTNAME at $TIMESTAMP"
source /users/jsyu/miniconda/etc/profile.d/conda.sh
conda activate dexmachina-5
wandb online
bash examples/train_rl_multi_demo.sh
